<?php
	
	//Read in variables from get request
	$Actuator = $_GET["Actuators"];

?>

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="styles/Act_Data_Sheet.css">
	<style type="text/css">
	</style>
	
</head>
<body>
	<div class="container">
		<div class="grid-container1">
			<div class="EN_logo"><img src="images/EN-image-3.png"></div>
			<div class="Client"><?php echo($Actuators); ?></div>
			<div class="Doc_Num">Document Number</div>
			<div class="Proj_Name">Project Name</div>
			<div class="Location">Location</div>
			<div class="Service">Service</div>
			<div class="Auto-valve" style="font-size: 20px;">Automated Valve</div>
			<div class="Rev">Rev</div>
			<div class="Date">Date</div>
			<div class="Issued_For">Issued For</div>
			<div class="By">By</div>
			<div class="Checked">Checked</div>
			<div class="Approved">Approved</div>
		</div>
		<div class="grid-container2">
		</div>
		<div class="grid-container3">
			<div class="header3">GENERAL / SERVICE CONDITIONS</div>
			<div class="header4">Power Requirements</div>
			<div class="column1">1.</div>
			<div class="column2">Number Required:</div>
			<div class="column3">One (1)</div>
			<div class="column4">39.</div>
			<div class="column5">Voltage / Phase / Hertz</div>
			<div class="column6">N/A</div>
			<div class="column7">N/A</div>
			<div class="column8">N/A</div>
			<div class="column1">2.</div>
			<div class="column2">P&ID No. / Section:</div>
			<div class="column3">N/A</div>
			<div class="column4">40.</div>
			<div class="column5">Horsepower / Speed / Full Load Amps</div>
			<div class="column6">N/A</div>
			<div class="column7">N/A</div>
			<div class="column8">N/A</div>
			<div class="column1">3.</div>
			<div class="column2">Line No. (Upstream)</div>
			<div class="column3">N/A</div>
			<div class="column4">41.</div>
			<div class="column5">Power Gas / Power Air Supply Pressure, psig</div>
			<div class="column9">Power Gas, 100</div>
			<div class="column1">4.</div>
			<div class="column2">Process Fluid Type</div>
			<div class="column3">Natural Gas</div>
			<div class="column4">42.</div>
			<div class="column5">Hydraulic Fluid Specification</div>
			<div class="column9">N/A</div>
			<div class="column1">5.</div>
			<div class="column2">Process Fluid Temp, F</div>
			<div class="column3">50 to 100</div>
			<div class="column4">43.</div>
			<div class="column5">Gas Displacement per Stroke (Cu.In)</div>
			<div class="column9">1631</div>
			<div class="column1">6.</div>
			<div class="column2">Ambient Temp Range, F</div>
			<div class="column3">-43 to 95</div>
			<div class="column4">44.</div>
			<div class="column5">Other</div>
			<div class="column9"></div>
			<div class="column1">7.</div>
			<div class="column2">Electrical Area Classification, Class/Division/Group</div>
			<div class="column10">|</div>
			<div class="column11">1</div>
			<div class="column12">D</div>
			<div class="column4">45.</div>
			<div class="column5">Other</div>
			<div class="column9"></div>
			<div class="column1">8.</div>
			<div class="column2">Location, Indoor/Outdoor</div>
			<div class="column3">Outdoor</div>
			<div class="header4">ACCESSORIES</div>
			<div class="header3">VALVE SPECIFICATION</div>
			<div class="column4">46.</div>
			<div class="column5">Pilot (Electrical, Pneumatic or Hydraulic)</div>
			<div class="column9">Electric</div>
			<div class="column1">9.</div>
			<div class="column2">Bare Valve Tag No. (SN)</div>
			<div class="column3">xxx</div>
			<div class="column4">47.</div>
			<div class="column5" >Pilot Voltage or Pressure</div>
			<div class="column9">24 VDC</div>
			<div class="column1">10.</div>
			<div class="column2">Valve Type</div>
			<div class="column3">xxx</div>
			<div class="column4">48.</div>
			<div class="column5" >Pilot Manufacturer</div>
			<div class="column9">Versa</div>
			<div class="column1">11.</div>
			<div class="column2">New or Existing?</div>
			<div class="column3">xxx</div>
			<div class="column4">49.</div>
			<div class="column5" >Pilot Model</div>
			<div class="column9">Versa</div>
			<div class="column1">12.</div>
			<div class="column2">Valve Manufacturer</div>
			<div class="column3">xxx</div>
			<div class="column4">50.</div>
			<div class="column5" >Local Reset Required?</div>
			<div class="column9">Yes</div>
			<div class="column1">13.</div>
			<div class="column2">Valve Model No.</div>
			<div class="column3">xxx</div>
			<div class="column4">51.</div>
			<div class="column5">Open Solenoid Operation (ETO, DTO, ETC, DTC)</div>
			<div class="column9">ETO</div>
			<div class="column1">14.</div>
			<div class="column2">Size (in)</div>
			<div class="column3">xxx</div>
			<div class="column4">52.</div>
			<div class="column5">Close Solenoid Operation (ETO, DTO, ETC, DTC)</div>
			<div class="column9">ETC</div>
			<div class="column1">15.</div>
			<div class="column2">ANSI Rating</div>
			<div class="column3">xxx</div>
			<div class="column4">53.</div>
			<div class="column5">Control Schematic No.</div>
			<div class="column9">ETC</div>
			<div class="column1">16.</div>
			<div class="column2">End Connections</div>
			<div class="column3">xxx</div>
			<div class="column4">54.</div>
			<div class="column5">Local Position Indicator</div>
			<div class="column9">Yes</div>
			<div class="column1">17.</div>
			<div class="column2">Maximum Allowable Stem Torque (MAST), in-lbf</div>
			<div class="column3">xxx</div>
			<div class="column4">55.</div>
			<div class="column5">Fail Position (Open, Closed or Last)</div>
			<div class="column9">Last</div>
			<div class="column1">18.</div>
			<div class="column2">Stem Design (2-pin / 4-pin)</div>
			<div class="column3">2-pin</div>
			<div class="column4">56.</div>
			<div class="column5">Limit Switch, Contact Type / No. Open / No. Closed</div>
			<div class="column6">N/A</div>
			<div class="column7">N/A</div>
			<div class="column8">N/A</div>
			<div class="column1">19.</div>
			<div class="column2">Maximum Differential Across Valve, psig</div>
			<div class="column3">xxx</div>
			<div class="column4">57.</div>
			<div class="column5">Limit Switches Manufacturer</div>
			<div class="column9">Westlock</div>
			<div class="column1">20.</div>
			<div class="column2">Valve Break Torque without Safety Factor, in-lbf</div>
			<div class="column3">xxx</div>
			<div class="column4">58.</div>
			<div class="column5">Limit Switches Model Number</div>
			<div class="column9">AccuTrak</div>
			<div class="column1">21.</div>
			<div class="column2">Valve Run Torque without Safety Factor, in-lbf</div>
			<div class="column3">xxx</div>
			<div class="column4">59.</div>
			<div class="column5">Auxiliary Switch</div>
			<div class="column9">AccuTrak</div>
			<div class="column1">22.</div>
			<div class="column2">Safety Factor (low temp factor included if required)</div>
			<div class="column3">1.5</div>
			<div class="column4">60.</div>
			<div class="column5">Speed Control</div>
			<div class="column9">Versa BC-3 (2)</div>
			<div class="column1">23.</div>
			<div class="column2">Design Break Torque with Safety Factor, in-lbf</div>
			<div class="column3">Vertical</div>
			<div class="column4">61.</div>
			<div class="column5">Surge Suppression Diode Across Solenoid Coil</div>
			<div class="column9">Yes</div>
			<div class="column1">24.</div>
			<div class="column2">Design Run Torque with Safety Factor, in-lbf</div>
			<div class="column3">xxx</div>
			<div class="column4">62.</div>
			<div class="column5">Hydraulic Override</div>
			<div class="column9">No</div>
			<div class="column1">25.</div>
			<div class="column2">Valve Mount (Horizontal / Vertical)</div>
			<div class="column3">xxx</div>
			<div class="column4">63.</div>
			<div class="column5">Jackscrew Override</div>
			<div class="column9">No</div>
			<div class="column1">26.</div>
			<div class="column2">Stem Mount (Horizontal / Vertical)</div>
			<div class="column3">xxx</div>
			<div class="column4">64.</div>
			<div class="column5">Stainless Steel Tag Bearing Valve Tag Number</div>
			<div class="column9">Yes</div>
			<div class="column1">27.</div>
			<div class="column2">Actuator Orientation to Pipe</div>
			<div class="column3">xxx</div>
			<div class="column4">65.</div>
			<div class="column5">Control Tubing Size / WT / Material</div>
			<div class="column9">3/8" x 0.049", 316 SS</div>
			<div class="column1">28.</div>
			<div class="column2">Extension Length, in</div>
			<div class="column3">N/A</div>
			<div class="column4">66.</div>
			<div class="column5">Control Tubing Fittings</div>
			<div class="column9">316 SS Swagelok</div>
			<div class="column1">29.</div>
			<div class="column2">Mounting Projection (Horizontal / Vertical)</div>
			<div class="column3">xxx</div>
			<div class="column4">67.</div>
			<div class="column5">Volume Tank</div>
			<div class="column9">No</div>
			<div class="header3">ACTUATOR SPECIFICATION</div>
			<div class="column4">68.</div>
			<div class="column5">Supply Valve</div>
			<div class="column9">Fisher 1301F-3</div>
			<div class="column1">30.</div>
			<div class="column2">Actuator Manufacturer</div>
			<div class="column3">xxx</div>
			<div class="column4">69.</div>
			<div class="column5">Supply Check Valve</div>
			<div class="column9">No</div>
			<div class="column1">31.</div>
			<div class="column2">Actuator Model No.</div>
			<div class="column3">xxx</div>
			<div class="column4">70.</div>
			<div class="column5">Supply Filters</div>
			<div class="column9">Welker F8</div>
			<div class="column1">32.</div>
			<div class="column2">Power (Pneumatic/Electric/Hydraulic/Gas-Hydraulic)</div>
			<div class="column3">xxx</div>
			<div class="column4">71.</div>
			<div class="column5">Supply Regulators</div>
			<div class="column9">Fisher 67CFR-226/SB</div>
			<div class="column1">33.</div>
			<div class="column2">Spring Return or Double Acting</div>
			<div class="column3">xxx</div>
			<div class="column4">72.</div>
			<div class="column5">Supply Relief Valves</div>
			<div class="column9">UCI-CV4 - 225psig</div>
			<div class="column1">34.</div>
			<div class="column2">Break Torque, in-lbf</div>
			<div class="column3">xxx</div>
			<div class="column4">73.</div>
			<div class="column5">Supply Relief Valves</div>
			<div class="column9">UCI-CV4 - 120psig</div>
			<div class="column1">35.</div>
			<div class="column2">Run Torque, in-lbf</div>
			<div class="column3">xxx</div>
			<div class="column4">74.</div>
			<div class="column5">Supply Pressure Gauge</div>
			<div class="column9">Blue Ribbon BR302L-254I</div>
			<div class="column1">36.</div>
			<div class="column2">Relief Break Torque, in-lb-f</div>
			<div class="column3">xxx</div>
			<div class="column4">75.</div>
			<div class="column5">Supply Pressure Gauge</div>
			<div class="column9">Blue Ribbon BR302L-254F</div>
			<div class="column1">37.</div>
			<div class="column2">Operating Time, sec</div>
			<div class="column3">xxx</div>
			<div class="column4">76.</div>
			<div class="column5">3-Way Ball Valve</div>
			<div class="column9">Swagelok SS-43GXF4-LL</div>
			<div class="column1">38.</div>
			<div class="column2">Other</div>
			<div class="column3">xxx</div>
			<div class="column4">77.</div>
			<div class="column5">Palm Buttons (lockable)</div>
			<div class="column9">Versa VSI-3301-LOVE-NGST</div>
			<div class="header5">COMMENTS</div>
		</div>	
		<div class="grid-container4">
			<div class="column41">78.</div>
			<div class="column42">Test</div>
			<div class="column41">79.</div>
			<div class="column42">Test</div>
			<div class="column41">80.</div>
			<div class="column42">Test</div>
			<div class="column41">81.</div>
			<div class="column42">Test</div>
			<div class="column41">82.</div>
			<div class="column42">Test</div>
			<div class="column41">83.</div>
			<div class="column42">Test</div>
			<div class="column41">84.</div>
			<div class="column42">Test</div>
			<div class="column41">85.</div>
			<div class="column42">Test</div>
			<div class="column41">86.</div>
			<div class="column42">Test</div>
			<div class="column41">87.</div>
			<div class="column42">Test</div>
			<div class="column41">88.</div>
			<div class="column42">Test</div>
			<div class="column41">89.</div>
			<div class="column42">Test</div>
			<div class="column41">90.</div>
			<div class="column42">Test</div>
			<div class="column41">91.</div>
			<div class="column42">Test</div>
			<div class="column41">92.</div>
			<div class="column42">Test</div>
			<div class="column41">93.</div>
			<div class="column42">Test</div>
			<div class="column41">94.</div>
			<div class="column42">Test</div>
		</div>
	</div>
</body>
</html>